"""
Anomaly detection in latent space
"""


class LatentLOFAnomalyScore:
    """
    Compute Local Outlier Factor (LOF) anomaly scores from raw spectra.
    Designed to serve as the classifier_fn for LimeSpectraExplainer.
    """

    def __init__(self, encoder_model, scaler_model, lof_model):
        """
        Initialize the LOF anomaly score pipeline.

        Parameters:
        encoder_model: Callable (e.g., autoencoder.encode) that takes 2D spectra
            and returns latent vectors.
        scaler_model: A pre-fitted sklearn StandardScaler used on the training
            latent space.
        lof_model: A trained sklearn LocalOutlierFactor model
            (MUST be trained with novelty=True).
        """
        self.encoder_function = encoder_model
        self.scaler = scaler_model
        self.lof_model = lof_model

    def score(self, spectra_batch):
        """
        Calculate the anomaly score for a batch of LIME-perturbed spectra.

        Parameters:
        spectra_batch (np.array): A batch of perturbed spectra generated by LIME.

        Returns:
        np.array: A 2D column vector of anomaly scores with shape (batch_size, 1).
        """
        # Strip LIME's extra RGB/image dimensions to get back to
        # (batch_size, num_fluxes)
        if spectra_batch.ndim > 2:
            clean_batch = spectra_batch[:, 0, :, 0]
        else:
            clean_batch = spectra_batch

        # Encode the raw spectra into the latent space
        latent_representations = self.encoder_function(clean_batch)

        # Scale using the PRE-FITTED scaler
        scaled_latent = self.scaler.transform(latent_representations)

        # Get raw anomaly scores from the LOF model
        # .score_samples() returns the negative outlier factor.
        if not hasattr(self.lof_model, "score_samples"):
            raise AttributeError(
                "The LOF model does not have 'score_samples'. "
                "Ensure it was initialized and trained with `novelty=True`."
            )

        raw_scores = self.lof_model.score_samples(scaled_latent)

        # - negative_outlier_factor is the anomaly score
        anomaly_scores = -1 * raw_scores

        # Reshape to a column vector so LIME can process it as a target variable
        return anomaly_scores.reshape(-1, 1)


class LatentIForestAnomalyScore:
    """
    A wrapper class to compute Isolation Forest anomaly scores from raw spectra.
    Designed to serve as the classifier_fn for LimeSpectraExplainer.
    """

    def __init__(self, encoder_model, scaler_model, iforest_model):
        """
        Initialize the iforest anomaly score pipeline.

        Parameters:
        encoder_function: Callable (e.g., autoencoder.encode) that takes 2D spectra
                          and returns latent vectors.
        scaler: A pre-fitted sklearn StandardScaler used on the training latent space.
        iforest_model: A trained sklearn IsolationForest model.
        """
        self.encoder = encoder_model
        self.scaler = scaler_model
        self.iforest_model = iforest_model

    def score(self, spectra_batch):
        """
        Calculate the anomaly score for a batch of LIME-perturbed spectra.

        Parameters:
        spectra_batch (np.array): A batch of perturbed spectra generated by LIME.
                                  May have shape (batch_size, 1, num_fluxes, 3).

        Returns:
        np.array: A 2D column vector of anomaly scores with shape (batch_size, 1).
        """
        # 1. Strip LIME's extra RGB/image dimensions to get back to
        # (batch_size, num_fluxes)
        if spectra_batch.ndim > 2:
            clean_batch = spectra_batch[:, 0, :, 0]
        else:
            clean_batch = spectra_batch

        # 2. Encode the raw spectra into the latent space
        latent_representations = self.encoder(clean_batch)

        # 3. Scale using the PRE-FITTED scaler
        scaled_latent = self.scaler.transform(latent_representations)

        # 4. Get raw anomaly scores from the Isolation Forest
        raw_scores = self.iforest_model.decision_function(scaled_latent)

        # 5. Negate the score to represent anomaly severity (higher = more anomalous)
        anomaly_scores = -1 * raw_scores

        # 6. Reshape to a column vector so LIME can process it as a target variable
        return anomaly_scores.reshape(-1, 1)
